server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xycrm?serverTimezone=Asia/Shanghai
    username: sad
    password: asd
  redis: # redis配置
    host: ip # IP
    port: 5555 # 端口
    password: asdsdff # 密码
    lettuce: # lettuce redis客户端配置
      pool: # 连接池配置
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: 200s # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
      com:
        huajframe:
          xycrm:
            mapper: debug